name: ExplicitExpansionCompanion

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup dotnet core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      - run: dotnet build
      - run: dotnet test
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: ExplicitExpansionCompanion/ExplicitExpansionCompanion.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          